sudo: required

dist: trusty
group: deprecated-2017Q4

services:
  - docker

script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - docker exec fidimag make test-basic
  - docker exec fidimag make codecov
  - docker exec fidimag make ipynb
  - kill %1

notifications:
  email:
    on_failure: always
