sudo: required

dist: trusty
group: deprecated-2017Q4

services:
  - docker

before_install:
  - docker build -t fidimag -f ./docker/travis/Dockerfile .
  - docker run -ti -d --name fidimag fidimag

jobs:
  - stage: Tests
    script: make test-docker
  - stage: Notebooks
    script: make ipynb-docker

notifications:
  email:
    on_failure: always
