sudo: required

dist: trusty
group: deprecated-2017Q4

services:
  - docker

before_install:
  - docker build -t fidimag -f ./docker/travis/Dockerfile .
  - docker run -ti -d --name fidimag fidimag

script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - docker exec fidimag make test-basic
  - docker exec fidimag make test-ipynb
  - kill %1

notifications:
  email:
    on_failure: always
